### ISSUE TITLE
Disordered region prediction using this package is different from the prediction using the RaptorX web server

### ISSUE THREAD

**Issue by DinghaiZheng** [realbigws/Predict_Property#1]
I tried to predict disordered regions in the following input protein sequence (saved in my_seq.fasta):
```
>my_seq
DIQMTQSPSSLSASVGDRVTITCRASQDVNTAVAWYQQKPGKAPKLLIYSASFLYSGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCQQHYTTPPTFGQGTKVEIKRTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGEC
```

The command I used was: ./Predict_Property.sh -i my_seq.fasta

In one of the output files (my_seq.diso), we can see that the positions 156~160 have high probabilities to be disordered.
```
 156 S * 0.993 
 157 G * 0.998 
 158 N * 0.999 
 159 S * 0.999 
 160 Q * 0.999 
```
 
However, if I use the [RaptorX web server](http://raptorx.uchicago.edu/StructurePropertyPred/predict/) to do the prediction using the same input sequence, the predicted disorder probability is much lower:
```
 156 S . 0.456 
 157 G * 0.511 
 158 N . 0.500 
 159 S . 0.421 
 160 Q . 0.307 
```

Based on what we know about my_seq, the prediction from the RaptorX web server is more likely to be correct. Could you check why the predictions are different?

Thank you very much!

**Comment by realbigws** [comment]
Hi, Dinghai.

I guess that you're using the "single sequence" version of Predict_Property
to predict the order/disorder regions.

If you switch to the "profile" version (i.e., first search for MSA and then
convert it to a TGT file), then you would probably obtain a similar result
as that from RaptorX_WebServer.

Best,
-Sheng

**Comment by DinghaiZheng** [comment]
Sheng,

Thank you for the quick response! 
I am following your suggestion now. It will take a while to download the Uniprot20 database, so I'll update you later. 

Best,
Dinghai

**Comment by DinghaiZheng** [comment]
Sheng,

After following your suggestion, the disordered region prediction using the command line is identical to the result from the webserver. 

Thank you very much for the software and suggestion!

Best,
Dinghai
